package com.example.bugrap.views;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class FeatureDescriptionDesign extends VerticalLayout {
	protected Button expandFeature;
	protected Label summary;
	protected NativeSelect priorities;
	protected NativeSelect types;
	protected NativeSelect statuses;
	protected NativeSelect users;
	protected NativeSelect versions;
	protected Button updateButton;
	protected Button revertButton;
	protected TextArea commentsList;

	public FeatureDescriptionDesign() {
		Design.read(this);
	}
}
