package com.example.bugrap.views;

import com.example.bugrap.components.DistributionBar;
import com.example.bugrap.components.FilterMenu;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.VerticalSplitPanel;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainPageDesign extends VerticalLayout {
	protected ComboBox projects;
	protected Button userButton;
	protected Button logoutButton;
	protected NativeSelect versions;
	protected DistributionBar distributionBar;
	protected FilterMenu userFilterMenu;
	protected FilterMenu statusFilterMenu;
	protected VerticalSplitPanel tableLayout;
	protected Table bugsTable;

	public MainPageDesign() {
		Design.read(this);
	}
}
